version: '3.4'
services:
  db:
    image: mongo:4.2.1
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dbdata: